import {
  Building2,
  TrendingUpDown,
  Coins,
  Wallet,
  Home,
  CreditCard,
} from 'lucide-react';
import { MdiDollar, HugeiconsHome04 } from '../../icons/icons';

export const ACCOUNT_TYPES_BY_CATEGORY = {
  ASSETS: [
    {
      id: 'cash',
      type: 'CHECKING',
      name: 'Cash Accounts',
      description: 'Checking, savings, money market, high-yield accounts',
      icon: MdiDollar,
      color: 'from-blue-500 to-blue-600',
      label: 'Cash',
      subtypes: [
        { value: 'CHECKING', label: 'Checking Account' },
        { value: 'SAVINGS', label: 'Savings Account' },
        { value: 'HIGH_YIELD_SAVINGS', label: 'High-Yield Savings' },
        { value: 'MONEY_MARKET', label: 'Money Market Account' },
        { value: 'CERTIFICATE_OF_DEPOSIT', label: 'Certificate of Deposit (CD)' },
        { value: 'CASH_MANAGEMENT', label: 'Cash Management Account' },
        { value: 'DIGITAL_WALLET', label: 'Digital Wallet' },
        { value: 'MOBILE_WALLET', label: 'Mobile Wallet' },
        { value: 'CASH_ON_HAND', label: 'Cash on Hand' },
        { value: 'PREPAID_CARD', label: 'Prepaid Card' },
      ],
    },
    {
      id: 'investments',
      type: 'RETIREMENT_401K',
      name: 'Investments & Retirement',
      description: '401k, IRA, brokerage, stocks, bonds, funds',
      icon: TrendingUpDown,
      color: 'from-green-500 to-green-600',
      label: 'Investments',
      subtypes: [
        { value: 'RETIREMENT_401K', label: '401(k) Plan' },
        { value: 'RETIREMENT_IRA_TRADITIONAL', label: 'Traditional IRA' },
        { value: 'RETIREMENT_IRA_ROTH', label: 'Roth IRA' },
        { value: 'RETIREMENT_403B', label: '403(b) Plan' },
        { value: 'RETIREMENT_457B', label: '457(b) Plan' },
        { value: 'RETIREMENT_IRA_SEP', label: 'SEP IRA' },
        { value: 'RETIREMENT_IRA_SIMPLE', label: 'SIMPLE IRA' },
        { value: 'BROKERAGE_ACCOUNT', label: 'Brokerage Account' },
        { value: 'MUTUAL_FUNDS', label: 'Mutual Funds' },
        { value: 'ETF', label: 'Exchange-Traded Fund (ETF)' },
        { value: 'STOCKS', label: 'Individual Stocks' },
        { value: 'BONDS', label: 'Bonds' },
        { value: 'TREASURY_SECURITIES', label: 'Treasury Securities' },
        { value: 'PENSION', label: 'Pension' },
        { value: 'ANNUITY', label: 'Annuity' },
        { value: 'EDUCATION_529_PLAN', label: '529 Education Plan' },
      ],
    },
    {
      id: 'realEstate',
      type: 'PRIMARY_RESIDENCE',
      name: 'Real Estate',
      description: 'Primary home, investment property, land, rentals',
      icon: HugeiconsHome04,
      color: 'from-amber-500 to-amber-600',
      label: 'Real Estate',
      subtypes: [
        { value: 'PRIMARY_RESIDENCE', label: 'Primary Home' },
        { value: 'INVESTMENT_PROPERTY', label: 'Investment Property' },
        { value: 'RENTAL_PROPERTY', label: 'Rental Property' },
        { value: 'VACATION_HOME', label: 'Vacation Home' },
        { value: 'LAND', label: 'Land' },
        { value: 'COMMERCIAL_PROPERTY', label: 'Commercial Property' },
        { value: 'INDUSTRIAL_PROPERTY', label: 'Industrial Property' },
        { value: 'TIMESHARE', label: 'Timeshare' },
        { value: 'DEVELOPMENT_LAND', label: 'Development Land' },
      ],
    },
    {
      id: 'vehicles',
      type: 'CAR',
      name: 'Vehicles',
      description: 'Cars, trucks, boats, motorcycles, aircraft',
      icon: Wallet,
      color: 'from-slate-500 to-slate-600',
      label: 'Vehicles',
      subtypes: [
        { value: 'CAR', label: 'Car' },
        { value: 'TRUCK', label: 'Truck' },
        { value: 'MOTORCYCLE', label: 'Motorcycle' },
        { value: 'BOAT', label: 'Boat' },
        { value: 'RV', label: 'RV (Recreational Vehicle)' },
        { value: 'AIRCRAFT', label: 'Aircraft' },
        { value: 'ELECTRIC_VEHICLE', label: 'Electric Vehicle' },
        { value: 'LUXURY_VEHICLE', label: 'Luxury Vehicle' },
        { value: 'CLASSIC_CAR', label: 'Classic Car' },
      ],
    },
    {
      id: 'valuables',
      type: 'JEWELRY',
      name: 'Valuables & Collections',
      description: 'Jewelry, art, collectibles, precious metals, watches',
      icon: Coins,
      color: 'from-yellow-500 to-yellow-600',
      label: 'Valuables',
      subtypes: [
        { value: 'JEWELRY', label: 'Jewelry' },
        { value: 'FINE_ART', label: 'Fine Art' },
        { value: 'COLLECTIBLES', label: 'Collectibles' },
        { value: 'ANTIQUES', label: 'Antiques' },
        { value: 'WATCHES', label: 'Watches' },
        { value: 'PRECIOUS_METALS', label: 'Precious Metals' },
        { value: 'GEMSTONES', label: 'Gemstones' },
        { value: 'WINE_COLLECTION', label: 'Wine Collection' },
      ],
    },
    {
      id: 'crypto',
      type: 'CRYPTO_WALLET_HOT',
      name: 'Cryptocurrency',
      description: 'Bitcoin, Ethereum, crypto wallets, DeFi, NFTs',
      icon: Coins,
      color: 'from-orange-500 to-orange-600',
      label: 'Crypto',
      subtypes: [
        { value: 'CRYPTO_WALLET_HOT', label: 'Hot Wallet' },
        { value: 'CRYPTO_WALLET_COLD', label: 'Cold Wallet (Hardware)' },
        { value: 'CRYPTO_EXCHANGE_ACCOUNT', label: 'Crypto Exchange Account' },
        { value: 'DEFI_PROTOCOL_POSITION', label: 'DeFi Protocol Position' },
        { value: 'STAKING_ACCOUNT', label: 'Staking Account' },
        { value: 'MINING_POOL_ACCOUNT', label: 'Mining Pool' },
        { value: 'NFT_COLLECTION', label: 'NFT Collection' },
        { value: 'MULTI_SIG_WALLET', label: 'Multi-Sig Wallet' },
      ],
    },
    {
      id: 'otherAssets',
      type: 'BUSINESS_OWNERSHIP',
      name: 'Other Assets',
      description: 'Business ownership, IP, stock options, insurance value',
      icon: Building2,
      color: 'from-purple-500 to-purple-600',
      label: 'Other Assets',
      subtypes: [
        { value: 'BUSINESS_OWNERSHIP', label: 'Business Ownership' },
        { value: 'PARTNERSHIP_INTEREST', label: 'Partnership Interest' },
        { value: 'STOCK_OPTIONS', label: 'Stock Options' },
        { value: 'RESTRICTED_STOCK', label: 'Restricted Stock' },
        { value: 'PATENTS_IP', label: 'Patents & Intellectual Property' },
        { value: 'LIFE_INSURANCE_VALUE', label: 'Life Insurance Cash Value' },
        { value: 'ACCOUNTS_RECEIVABLE', label: 'Accounts Receivable' },
        { value: 'EMPLOYEE_STOCK_PURCHASE', label: 'ESPP' },
      ],
    },
  ],
  LIABILITIES: [
    {
      id: 'creditcards',
      type: 'PERSONAL_CREDIT_CARD',
      name: 'Credit Cards',
      description: 'Personal, business, store, gas credit cards',
      icon: CreditCard,
      color: 'from-red-500 to-red-600',
      label: 'Credit Cards',
      subtypes: [
        { value: 'PERSONAL_CREDIT_CARD', label: 'Personal Credit Card' },
        { value: 'BUSINESS_CREDIT_CARD', label: 'Business Credit Card' },
        { value: 'SECURED_CREDIT_CARD', label: 'Secured Credit Card' },
        { value: 'STORE_CREDIT_CARD', label: 'Store Credit Card' },
        { value: 'GAS_CREDIT_CARD', label: 'Gas Credit Card' },
        { value: 'CHARGE_CARD', label: 'Charge Card' },
      ],
    },
    {
      id: 'mortgages',
      type: 'MORTGAGE_PRIMARY',
      name: 'Mortgages',
      description: 'Home mortgage, equity lines, construction loans',
      icon: Home,
      color: 'from-pink-500 to-pink-600',
      label: 'Mortgages',
      subtypes: [
        { value: 'MORTGAGE_PRIMARY', label: 'Primary Mortgage' },
        { value: 'MORTGAGE_RENTAL', label: 'Rental Property Mortgage' },
        { value: 'MORTGAGE_SECOND_HOME', label: 'Second Home Mortgage' },
        { value: 'HOME_EQUITY_LOAN', label: 'Home Equity Loan' },
        { value: 'HOME_EQUITY_LINE', label: 'Home Equity Line of Credit' },
        { value: 'CONSTRUCTION_LOAN', label: 'Construction Loan' },
        { value: 'BRIDGE_LOAN', label: 'Bridge Loan' },
      ],
    },
    {
      id: 'loans',
      type: 'PERSONAL_LOAN',
      name: 'Personal & Business Loans',
      description: 'Personal loans, auto loans, student loans, business loans',
      icon: Building2,
      color: 'from-orange-500 to-orange-600',
      label: 'Loans',
      subtypes: [
        { value: 'PERSONAL_LOAN', label: 'Personal Loan' },
        { value: 'STUDENT_LOAN', label: 'Student Loan' },
        { value: 'AUTO_LOAN', label: 'Auto Loan' },
        { value: 'BUSINESS_LOAN', label: 'Business Loan' },
        { value: 'BOAT_LOAN', label: 'Boat Loan' },
        { value: 'RV_LOAN', label: 'RV Loan' },
        { value: 'CONSOLIDATED_LOAN', label: 'Consolidated Loan' },
        { value: 'PAYDAY_LOAN', label: 'Payday Loan' },
        { value: 'PEER_TO_PEER_LOAN', label: 'Peer-to-Peer Loan' },
      ],
    },
    {
      id: 'otherLiabilities',
      type: 'ACCOUNT_PAYABLE',
      name: 'Other Liabilities',
      description: 'Tax payable, accrued expenses, legal settlements',
      icon: CreditCard,
      color: 'from-red-700 to-red-800',
      label: 'Other Liabilities',
      subtypes: [
        { value: 'ACCOUNT_PAYABLE', label: 'Accounts Payable' },
        { value: 'TAX_PAYABLE', label: 'Tax Payable' },
        { value: 'ACCRUED_EXPENSE', label: 'Accrued Expenses' },
        { value: 'LEGAL_SETTLEMENT', label: 'Legal Settlement' },
        { value: 'BUSINESS_PAYABLE', label: 'Business Payables' },
        { value: 'PENSION_LIABILITY', label: 'Pension Liability' },
        { value: 'DEFERRED_REVENUE', label: 'Deferred Revenue' },
        { value: 'LEASE_LIABILITY', label: 'Lease Liability' },
      ],
    },
  ],
};
