import { ACCOUNT_TYPE_SUBTYPES, ASSET_TYPES, BANK_ACCOUNT_TYPES } from './constants';

export const getSubtypeKeyForType = (accountType: string): string | null => {
  const typeMap: Record<string, string> = {
    'CHECKING': 'CHECKING',
    'SAVINGS': 'SAVINGS',
    'HIGH_YIELD_SAVINGS': 'CHECKING',
    'MONEY_MARKET': 'CHECKING',
    'CERTIFICATE_OF_DEPOSIT': 'CHECKING',
    'CASH_MANAGEMENT': 'CHECKING',
    'PREPAID_CARD': 'CHECKING',
    'DIGITAL_WALLET': 'CHECKING',
    'MOBILE_WALLET': 'CHECKING',
    'CASH_ON_HAND': 'CHECKING',
    'FOREIGN_CURRENCY_ACCOUNT': 'CHECKING',
    'PAYMENT_PROCESSOR_BALANCE': 'CHECKING',
    'PETTY_CASH': 'CHECKING',
    'ESCROW_ACCOUNT': 'CHECKING',
    'RETIREMENT_401K': 'INVESTMENT',
    'RETIREMENT_IRA_TRADITIONAL': 'INVESTMENT',
    'RETIREMENT_IRA_ROTH': 'INVESTMENT',
    'RETIREMENT_403B': 'INVESTMENT',
    'RETIREMENT_457B': 'INVESTMENT',
    'RETIREMENT_IRA_SEP': 'INVESTMENT',
    'RETIREMENT_IRA_SIMPLE': 'INVESTMENT',
    'BROKERAGE_ACCOUNT': 'INVESTMENT',
    'MUTUAL_FUNDS': 'INVESTMENT',
    'ETF': 'INVESTMENT',
    'STOCKS': 'INVESTMENT',
    'BONDS': 'INVESTMENT',
    'TREASURY_SECURITIES': 'INVESTMENT',
    'PENSION': 'INVESTMENT',
    'ANNUITY': 'INVESTMENT',
    'EDUCATION_529_PLAN': 'INVESTMENT',
    'PRIMARY_RESIDENCE': 'REAL_ESTATE',
    'INVESTMENT_PROPERTY': 'REAL_ESTATE',
    'VACATION_HOME': 'REAL_ESTATE',
    'RENTAL_PROPERTY': 'REAL_ESTATE',
    'TIMESHARE': 'REAL_ESTATE',
    'LAND': 'REAL_ESTATE',
    'COMMERCIAL_PROPERTY': 'REAL_ESTATE',
    'INDUSTRIAL_PROPERTY': 'REAL_ESTATE',
    'DEVELOPMENT_LAND': 'REAL_ESTATE',
    'CAR': 'VEHICLE',
    'TRUCK': 'VEHICLE',
    'MOTORCYCLE': 'VEHICLE',
    'RV': 'VEHICLE',
    'BOAT': 'VEHICLE',
    'AIRCRAFT': 'VEHICLE',
    'BICYCLE': 'VEHICLE',
    'ELECTRIC_VEHICLE': 'VEHICLE',
    'LUXURY_VEHICLE': 'VEHICLE',
    'CLASSIC_CAR': 'VEHICLE',
    'COMMERCIAL_VEHICLE': 'VEHICLE',
    'ATV': 'VEHICLE',
    'SCOOTER': 'VEHICLE',
    'JEWELRY': 'OTHER_ASSET',
    'FINE_ART': 'OTHER_ASSET',
    'COLLECTIBLES': 'OTHER_ASSET',
    'ANTIQUES': 'OTHER_ASSET',
    'WATCHES': 'OTHER_ASSET',
    'PRECIOUS_METALS': 'OTHER_ASSET',
    'GEMSTONES': 'OTHER_ASSET',
    'FIREARMS': 'OTHER_ASSET',
    'MEMORABILIA': 'OTHER_ASSET',
    'WINE_COLLECTION': 'OTHER_ASSET',
    'SPORTS_EQUIPMENT': 'OTHER_ASSET',
    'CRYPTO_WALLET_HOT': 'CRYPTO',
    'CRYPTO_WALLET_COLD': 'CRYPTO',
    'CRYPTO_EXCHANGE_ACCOUNT': 'CRYPTO',
    'DEFI_PROTOCOL_POSITION': 'CRYPTO',
    'STAKING_ACCOUNT': 'CRYPTO',
    'MINING_POOL_ACCOUNT': 'CRYPTO',
    'NFT_COLLECTION': 'CRYPTO',
    'WRAPPED_ASSET_ACCOUNT': 'CRYPTO',
    'MULTI_SIG_WALLET': 'CRYPTO',
    'BUSINESS_OWNERSHIP': 'OTHER_ASSET',
    'PARTNERSHIP_INTEREST': 'OTHER_ASSET',
    'STOCK_OPTIONS': 'OTHER_ASSET',
    'RESTRICTED_STOCK': 'OTHER_ASSET',
    'PATENTS_IP': 'OTHER_ASSET',
    'ACCOUNTS_RECEIVABLE': 'OTHER_ASSET',
    'NOTES_RECEIVABLE': 'OTHER_ASSET',
    'LIFE_INSURANCE_VALUE': 'OTHER_ASSET',
    'EMPLOYEE_STOCK_PURCHASE': 'OTHER_ASSET',
    'ROYALTY_INTEREST': 'OTHER_ASSET',
    'TIMBER_RIGHTS': 'OTHER_ASSET',
    'MINERAL_RIGHTS': 'OTHER_ASSET',
    'PERSONAL_CREDIT_CARD': 'CREDIT_CARD',
    'BUSINESS_CREDIT_CARD': 'CREDIT_CARD',
    'SECURED_CREDIT_CARD': 'CREDIT_CARD',
    'STORE_CREDIT_CARD': 'CREDIT_CARD',
    'GAS_CREDIT_CARD': 'CREDIT_CARD',
    'CHARGE_CARD': 'CREDIT_CARD',
    'PREPAID_CREDIT_CARD': 'CREDIT_CARD',
    'MORTGAGE_PRIMARY': 'MORTGAGE',
    'MORTGAGE_SECOND_HOME': 'MORTGAGE',
    'MORTGAGE_RENTAL': 'MORTGAGE',
    'HOME_EQUITY_LOAN': 'MORTGAGE',
    'HOME_EQUITY_LINE': 'MORTGAGE',
    'CONSTRUCTION_LOAN': 'MORTGAGE',
    'BRIDGE_LOAN': 'MORTGAGE',
    'PERSONAL_LOAN': 'LOAN',
    'BUSINESS_LOAN': 'LOAN',
    'STUDENT_LOAN': 'LOAN',
    'AUTO_LOAN': 'LOAN',
    'BOAT_LOAN': 'LOAN',
    'RV_LOAN': 'LOAN',
    'CONSOLIDATED_LOAN': 'LOAN',
    'PAYDAY_LOAN': 'LOAN',
    'PEER_TO_PEER_LOAN': 'LOAN',
  };
  return typeMap[accountType] || null;
};

export const getSubtypesForAccountType = (accountType: string): string[] => {
  const key = getSubtypeKeyForType(accountType);
  return key ? ACCOUNT_TYPE_SUBTYPES[key]?.subtypes || [] : [];
};

export const formatEnumLabel = (value: string): string => {
  return value
    .split('_')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join(' ');
};

export const shouldShowBankStatementUpload = (accountType: string): boolean => {
  return BANK_ACCOUNT_TYPES.includes(accountType);
};

export const shouldShowAssetFields = (accountType: string): boolean => {
  return ASSET_TYPES.includes(accountType);
};
