export const CURRENCIES = [
  { value: 'USD', label: 'USD ($)' },
  { value: 'EUR', label: 'EUR (€)' },
  { value: 'GBP', label: 'GBP (£)' },
  { value: 'CAD', label: 'CAD ($)' },
  { value: 'AUD', label: 'AUD ($)' },
  { value: 'JPY', label: 'JPY (¥)' },
  { value: 'PKR', label: 'PKR (Rs)' },
];

export const POPULAR_CONNECTIONS = [
  { name: 'Chase', category: 'Bank', logo: 'chase.com' },
  { name: 'Bank of America', category: 'Bank', logo: 'bofa.com' },
  { name: 'Wells Fargo', category: 'Bank', logo: 'wells-fargo.com' },
  { name: 'US Bank', category: 'Bank', logo: 'usbank.com' },
  { name: 'TD Bank', category: 'Bank', logo: 'td.com' },
  { name: 'Capital One', category: 'Bank', logo: 'capitalone.com' },
  { name: 'Fidelity', category: 'Brokerage', logo: 'fidelity.com' },
  { name: 'Vanguard', category: 'Brokerage', logo: 'vanguard.com' },
  { name: 'Charles Schwab', category: 'Brokerage', logo: 'charles-schwab.com' },
  { name: 'Discover', category: 'Credit Card', logo: 'discover.com' },
];

export const ACCOUNT_TYPE_SUBTYPES: Record<string, { label: string; subtypes: string[] }> = {
  CHECKING: {
    label: 'Cash Account',
    subtypes: ['STANDARD', 'INTEREST_BEARING', 'STUDENT', 'HIGH_YIELD', 'MONEY_MARKET', 'GIFT_CARD', 'TRAVEL', 'RELOADABLE', 'SWEEP', 'TREASURY', 'LIQUIDITY_POOL'],
  },
  SAVINGS: {
    label: 'Cash Account',
    subtypes: ['STANDARD', 'INTEREST_BEARING', 'STUDENT', 'HIGH_YIELD', 'MONEY_MARKET', 'GIFT_CARD', 'TRAVEL', 'RELOADABLE', 'SWEEP', 'TREASURY', 'LIQUIDITY_POOL'],
  },
  INVESTMENT: {
    label: 'Investment Account',
    subtypes: ['STANDARD', 'MARGIN', 'COMMISSION_FREE', 'TAXABLE', 'CUSTODIAL', 'TRADITIONAL', 'ROTH', 'SAFE_HARBOR', 'SEP', 'ROLLOVER', 'INHERITED', 'ACTIVE', 'INDEX', 'TARGET_DATE', 'GOVERNMENT', 'MUNICIPAL', 'ZERO_COUPON', 'HEDGE_FUND', 'PRIVATE_EQUITY', 'PRIVATE_CREDIT', 'VESTED', 'UNVESTED'],
  },
  CRYPTO: {
    label: 'Crypto Account',
    subtypes: ['ETHEREUM', 'BITCOIN', 'SOLANA', 'POLYGON', 'AVALANCHE', 'OPTIMISM', 'ARBITRUM', 'BASE', 'ZKSYNC', 'SCROLL', 'LINEA', 'AAVE', 'CURVE', 'UNISWAP', 'BALANCER', 'COMPOUND', 'MAKERDAO'],
  },
  REAL_ESTATE: {
    label: 'Asset Account',
    subtypes: ['PRIMARY_RESIDENCE', 'RENTAL', 'COMMERCIAL', 'LAND', 'VACATION_HOME', 'AUTO', 'MOTORCYCLE', 'BOAT', 'RV', 'AIRCRAFT', 'EQUIPMENT', 'FINE_ART', 'VINTAGE_ART', 'SCULPTURES', 'ANTIQUES', 'MEMORABILIA', 'WINE', 'SPORTS_MEMORABILIA', 'COMIC_BOOKS', 'TRADING_CARDS', 'WATCHES', 'JEWELRY', 'STAMPS', 'GOLD_BULLION', 'GOLD_COINS', 'SILVER_BULLION', 'SILVER_COINS', 'PLATINUM', 'PALLADIUM', 'PATENT', 'TRADEMARK', 'COPYRIGHT', 'TRADE_SECRET', 'DOMAIN_NAME', 'BRAND', 'SOLE_PROPRIETOR', 'LLC', 'S_CORP', 'C_CORP', 'PARTNERSHIP', 'STARTUP_EQUITY', 'WHOLE_LIFE', 'UNIVERSAL_LIFE', 'VARIABLE_LIFE', 'INDEXED_LIFE', 'PENSION', 'ANNUITY', 'IMMEDIATE_ANNUITY', 'DEFERRED_ANNUITY'],
  },
  VEHICLE: {
    label: 'Asset Account',
    subtypes: ['AUTO', 'MOTORCYCLE', 'BOAT', 'RV', 'AIRCRAFT'],
  },
  OTHER_ASSET: {
    label: 'Asset Account',
    subtypes: ['EQUIPMENT', 'FINE_ART', 'VINTAGE_ART', 'SCULPTURES', 'ANTIQUES', 'MEMORABILIA', 'WINE', 'SPORTS_MEMORABILIA', 'COMIC_BOOKS', 'TRADING_CARDS', 'WATCHES', 'JEWELRY', 'STAMPS', 'GOLD_BULLION', 'GOLD_COINS', 'SILVER_BULLION', 'SILVER_COINS', 'PLATINUM', 'PALLADIUM'],
  },
  CREDIT_CARD: {
    label: 'Credit Account',
    subtypes: ['PERSONAL', 'BUSINESS', 'CORPORATE', 'NO_ANNUAL_FEE', 'HELOC', 'PERSONAL_LOC', 'BUSINESS_LOC', 'FEDERAL', 'PRIVATE', 'PARENT_PLUS', 'CONSOLIDATION', 'INCOME', 'PROPERTY', 'CORPORATE_TAX', 'QUARTERLY_EST', 'MONTHLY', 'ANNUAL', 'PROFESSIONAL'],
  },
  LOAN: {
    label: 'Loan Account',
    subtypes: ['PRIMARY_RESIDENCE_MORTGAGE', 'INVESTMENT_PROPERTY', 'CONSTRUCTION_LOAN', 'ARM', 'FIXED_RATE', 'AUTO', 'MOTORCYCLE', 'BOAT', 'RV', 'UNSECURED', 'SECURED', 'DEBT_CONSOLIDATION', 'PAYDAY', 'FEDERAL', 'PRIVATE', 'PARENT_PLUS', 'PERKINS', 'STAFFORD', 'CONSOLIDATION', 'INCOME_TAX', 'PROPERTY_TAX', 'CORPORATE_TAX', 'SALES_TAX', 'PAYROLL_TAX', 'QUARTERLY_EST', 'MONTHLY', 'ANNUAL', 'QUARTERLY', 'PROFESSIONAL_SERVICE', 'MEMBERSHIP', 'SETTLEMENT', 'JUDGMENT', 'CHILD_SUPPORT', 'ALIMONY', 'CONTRACT_OBLIGATION', 'BOND_ISSUANCE', 'NOTE', 'DEBENTURE', 'CONVERTIBLE_DEBT'],
  },
  MORTGAGE: {
    label: 'Loan Account',
    subtypes: ['PRIMARY_RESIDENCE_MORTGAGE', 'INVESTMENT_PROPERTY', 'CONSTRUCTION_LOAN', 'ARM', 'FIXED_RATE'],
  },
};

export const ASSET_TYPES = [
  'PRIMARY_RESIDENCE', 'INVESTMENT_PROPERTY', 'RENTAL_PROPERTY', 'VACATION_HOME', 'LAND',
  'COMMERCIAL_PROPERTY', 'INDUSTRIAL_PROPERTY', 'TIMESHARE', 'DEVELOPMENT_LAND',
  'CAR', 'TRUCK', 'MOTORCYCLE', 'BOAT', 'RV', 'AIRCRAFT', 'ELECTRIC_VEHICLE', 'LUXURY_VEHICLE', 'CLASSIC_CAR',
  'JEWELRY', 'FINE_ART', 'COLLECTIBLES', 'ANTIQUES', 'WATCHES', 'PRECIOUS_METALS', 'GEMSTONES', 'WINE_COLLECTION',
  'BUSINESS_OWNERSHIP', 'PARTNERSHIP_INTEREST', 'STOCK_OPTIONS', 'RESTRICTED_STOCK', 'PATENTS_IP',
  'LIFE_INSURANCE_VALUE', 'ACCOUNTS_RECEIVABLE', 'EMPLOYEE_STOCK_PURCHASE'
];

export const BANK_ACCOUNT_TYPES = ['CHECKING', 'SAVINGS', 'HIGH_YIELD_SAVINGS', 'MONEY_MARKET', 'CERTIFICATE_OF_DEPOSIT', 'CASH_MANAGEMENT', 'DIGITAL_WALLET', 'MOBILE_WALLET', 'CASH_ON_HAND', 'PREPAID_CARD'];

export const INVESTMENT_ACCOUNT_TYPES = [
  'RETIREMENT_401K', 'RETIREMENT_IRA_TRADITIONAL', 'RETIREMENT_IRA_ROTH', 'RETIREMENT_403B', 'RETIREMENT_457B',
  'RETIREMENT_IRA_SEP', 'RETIREMENT_IRA_SIMPLE', 'BROKERAGE_ACCOUNT', 'MUTUAL_FUNDS', 'ETF', 'STOCKS',
  'BONDS', 'TREASURY_SECURITIES', 'PENSION', 'ANNUITY', 'EDUCATION_529_PLAN'
];

export const CREDIT_CARD_TYPES = [
  'PERSONAL_CREDIT_CARD', 'BUSINESS_CREDIT_CARD', 'SECURED_CREDIT_CARD', 'STORE_CREDIT_CARD',
  'GAS_CREDIT_CARD', 'CHARGE_CARD'
];

export const MORTGAGE_TYPES = [
  'MORTGAGE_PRIMARY', 'MORTGAGE_RENTAL', 'MORTGAGE_SECOND_HOME', 'HOME_EQUITY_LOAN',
  'HOME_EQUITY_LINE', 'CONSTRUCTION_LOAN', 'BRIDGE_LOAN'
];

export const LOAN_TYPES = [
  'PERSONAL_LOAN', 'STUDENT_LOAN', 'AUTO_LOAN', 'BUSINESS_LOAN', 'BOAT_LOAN', 'RV_LOAN',
  'CONSOLIDATED_LOAN', 'PAYDAY_LOAN', 'PEER_TO_PEER_LOAN'
];

export const OTHER_LIABILITY_TYPES = [
  'ACCOUNT_PAYABLE', 'TAX_PAYABLE', 'ACCRUED_EXPENSE', 'LEGAL_SETTLEMENT', 'BUSINESS_PAYABLE',
  'PENSION_LIABILITY', 'DEFERRED_REVENUE', 'LEASE_LIABILITY'
];

export const CRYPTO_TYPES = [
  'CRYPTO_WALLET_HOT', 'CRYPTO_WALLET_COLD', 'CRYPTO_EXCHANGE_ACCOUNT', 'DEFI_PROTOCOL_POSITION',
  'STAKING_ACCOUNT', 'MINING_POOL_ACCOUNT', 'NFT_COLLECTION', 'MULTI_SIG_WALLET'
];
